/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder2;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JSlider;
import sun.security.util.Length;

/**
 *
 * @author saipr
 */
public class CMainTestColorPanel extends javax.swing.JPanel
{

    CTestColorPanel panel;

    /**
     * Creates new form TodoAlv
     */
    public CMainTestColorPanel()
    {

        initComponents();
        panel = new CTestColorPanel();
        panel.setVisible(true);
        this.add(panel, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        vPnlR = new javax.swing.JPanel();
        vSliderR = new javax.swing.JSlider();
        vTxtFieldR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        vPnlG = new javax.swing.JPanel();
        vSliderG = new javax.swing.JSlider();
        vTxtFieldG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        vPnlB = new javax.swing.JPanel();
        vSliderB = new javax.swing.JSlider();
        vTxtFieldB = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel7.setLayout(new java.awt.BorderLayout());

        vPnlR.setBackground(new java.awt.Color(100, 0, 0));

        vSliderR.setMaximum(255);
        vSliderR.setValue(100);
        vSliderR.setOpaque(false);
        vSliderR.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSliderRStateChanged(evt);
            }
        });
        vPnlR.add(vSliderR);

        vTxtFieldR.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        vTxtFieldR.setText("100");
        vTxtFieldR.setBorder(null);
        vTxtFieldR.setSelectionColor(new java.awt.Color(255, 255, 255));
        vTxtFieldR.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                vTxtFieldRKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTxtFieldRKeyTyped(evt);
            }
        });
        vPnlR.add(vTxtFieldR);

        jPanel7.add(vPnlR, java.awt.BorderLayout.CENTER);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("R");
        jLabel1.setOpaque(true);
        jPanel7.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel7);

        jPanel6.setLayout(new java.awt.BorderLayout());

        vPnlG.setBackground(new java.awt.Color(0, 100, 0));

        vSliderG.setMaximum(255);
        vSliderG.setValue(100);
        vSliderG.setOpaque(false);
        vSliderG.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSliderGStateChanged(evt);
            }
        });
        vPnlG.add(vSliderG);

        vTxtFieldG.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        vTxtFieldG.setText("100");
        vTxtFieldG.setBorder(null);
        vTxtFieldG.setSelectionColor(new java.awt.Color(255, 255, 255));
        vTxtFieldG.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                vTxtFieldGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTxtFieldGKeyTyped(evt);
            }
        });
        vPnlG.add(vTxtFieldG);

        jPanel6.add(vPnlG, java.awt.BorderLayout.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("G");
        jPanel6.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("B");
        jLabel3.setOpaque(true);
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        vPnlB.setBackground(new java.awt.Color(0, 0, 100));

        vSliderB.setMaximum(255);
        vSliderB.setValue(100);
        vSliderB.setOpaque(false);
        vSliderB.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSliderBStateChanged(evt);
            }
        });
        vPnlB.add(vSliderB);

        vTxtFieldB.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        vTxtFieldB.setText("100");
        vTxtFieldB.setBorder(null);
        vTxtFieldB.setSelectionColor(new java.awt.Color(255, 255, 255));
        vTxtFieldB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                vTxtFieldBKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                vTxtFieldBKeyTyped(evt);
            }
        });
        vPnlB.add(vTxtFieldB);

        jPanel5.add(vPnlB, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel5);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void vSliderRStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSliderRStateChanged
    {//GEN-HEADEREND:event_vSliderRStateChanged
        panel.red = ((JSlider) (evt.getSource())).getValue();
        vTxtFieldR.setText(String.valueOf(((JSlider) (evt.getSource())).getValue()));
        vPnlR.setBackground(new Color(Integer.valueOf(((JSlider) (evt.getSource())).getValue()), 0, 0));
        panel.repaint();
    }//GEN-LAST:event_vSliderRStateChanged

    private void vSliderGStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSliderGStateChanged
    {//GEN-HEADEREND:event_vSliderGStateChanged
        panel.green = ((JSlider) (evt.getSource())).getValue();
        vTxtFieldG.setText(String.valueOf(((JSlider) (evt.getSource())).getValue()));
        vPnlG.setBackground(new Color(0, Integer.valueOf(((JSlider) (evt.getSource())).getValue()), 0));
        panel.repaint();
    }//GEN-LAST:event_vSliderGStateChanged

    private void vSliderBStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSliderBStateChanged
    {//GEN-HEADEREND:event_vSliderBStateChanged
        panel.blue = ((JSlider) (evt.getSource())).getValue();
        vTxtFieldB.setText(String.valueOf(((JSlider) (evt.getSource())).getValue()));
        vPnlB.setBackground(new Color(0, 0, Integer.valueOf(((JSlider) (evt.getSource())).getValue())));
        panel.repaint();
    }//GEN-LAST:event_vSliderBStateChanged

    private void vTxtFieldRKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldRKeyTyped
    {//GEN-HEADEREND:event_vTxtFieldRKeyTyped
        if ((vTxtFieldR.getText().length() >= 3))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTxtFieldRKeyTyped

    private void vTxtFieldRKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldRKeyReleased
    {//GEN-HEADEREND:event_vTxtFieldRKeyReleased
        try
        {
            if (Integer.valueOf(vTxtFieldR.getText()) > 255 && !vTxtFieldR.getText().isEmpty())
            {
                vTxtFieldR.setText("255");
            }
            vSliderR.setValue(Integer.valueOf(vTxtFieldR.getText()));
        } catch (Exception e)
        {
            vSliderR.setValue(0);
        }

    }//GEN-LAST:event_vTxtFieldRKeyReleased

    private void vTxtFieldGKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldGKeyReleased
    {//GEN-HEADEREND:event_vTxtFieldGKeyReleased
        try
        {
            if (Integer.valueOf(vTxtFieldG.getText()) > 255 && !vTxtFieldG.getText().isEmpty())
            {
                vTxtFieldG.setText("255");
            }
            vSliderG.setValue(Integer.valueOf(vTxtFieldG.getText()));
        } catch (Exception e)
        {
            vSliderG.setValue(0);
        }
    }//GEN-LAST:event_vTxtFieldGKeyReleased

    private void vTxtFieldGKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldGKeyTyped
    {//GEN-HEADEREND:event_vTxtFieldGKeyTyped
        if ((vTxtFieldG.getText().length() >= 3))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTxtFieldGKeyTyped

    private void vTxtFieldBKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldBKeyReleased
    {//GEN-HEADEREND:event_vTxtFieldBKeyReleased
        try
        {
            if (Integer.valueOf(vTxtFieldB.getText()) > 255 && !vTxtFieldB.getText().isEmpty())
            {
                vTxtFieldB.setText("255");
            }
            vSliderB.setValue(Integer.valueOf(vTxtFieldB.getText()));
        } catch (Exception e)
        {
            vSliderB.setValue(0);
        }
    }//GEN-LAST:event_vTxtFieldBKeyReleased

    private void vTxtFieldBKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_vTxtFieldBKeyTyped
    {//GEN-HEADEREND:event_vTxtFieldBKeyTyped
        if ((vTxtFieldB.getText().length() >= 3))
        {
            evt.consume();
        }
    }//GEN-LAST:event_vTxtFieldBKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel vPnlB;
    private javax.swing.JPanel vPnlG;
    private javax.swing.JPanel vPnlR;
    private javax.swing.JSlider vSliderB;
    private javax.swing.JSlider vSliderG;
    private javax.swing.JSlider vSliderR;
    private javax.swing.JTextField vTxtFieldB;
    private javax.swing.JTextField vTxtFieldG;
    private javax.swing.JTextField vTxtFieldR;
    // End of variables declaration//GEN-END:variables
}
