/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder2;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 * @author saipr
 */
public class CPnlDrawShapesMod extends javax.swing.JPanel
{

    JavaDraw2DPanel panel = null;

    /**
     * Creates new form CPnlDrawShapes
     */
    public CPnlDrawShapesMod()
    {
        initComponents();
        panel = new JavaDraw2DPanel();
        vPnlCent.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        vTgbtn_Fig1 = new javax.swing.JToggleButton();
        vTgbtn_Fig2 = new javax.swing.JToggleButton();
        vTgbtn_Fig3 = new javax.swing.JToggleButton();
        vTgbtn_Fig4 = new javax.swing.JToggleButton();
        vTgbtn_Fig5 = new javax.swing.JToggleButton();
        vTgbtn_Fig6 = new javax.swing.JToggleButton();
        vTgbtn_Fig7 = new javax.swing.JToggleButton();
        vTgbtn_Fig8 = new javax.swing.JToggleButton();
        vTgbtn_Fig9 = new javax.swing.JToggleButton();
        vTgbtn_Fig10 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        vTgbtn_LimpiarPantalla = new javax.swing.JButton();
        vCmbox_ColorDibujado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        vPnlCent = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new java.awt.GridLayout(4, 0));

        vTgbtn_Fig1.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig1);
        vTgbtn_Fig1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig1.setSelected(true);
        vTgbtn_Fig1.setText("Figura 1");
        vTgbtn_Fig1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig1ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig1);

        vTgbtn_Fig2.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig2);
        vTgbtn_Fig2.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig2.setText("Figura 2");
        vTgbtn_Fig2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig2ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig2);

        vTgbtn_Fig3.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig3);
        vTgbtn_Fig3.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig3.setText("Figura 3");
        vTgbtn_Fig3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig3ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig3);

        vTgbtn_Fig4.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig4);
        vTgbtn_Fig4.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig4.setText("Figura 4");
        vTgbtn_Fig4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig4ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig4);

        vTgbtn_Fig5.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig5);
        vTgbtn_Fig5.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig5.setText("Figura 5");
        vTgbtn_Fig5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig5ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig5);

        vTgbtn_Fig6.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig6);
        vTgbtn_Fig6.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig6.setText("Figura 6");
        vTgbtn_Fig6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig6ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig6);

        vTgbtn_Fig7.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig7);
        vTgbtn_Fig7.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig7.setText("Figura 7");
        vTgbtn_Fig7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig7ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig7);

        vTgbtn_Fig8.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig8);
        vTgbtn_Fig8.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig8.setText("Bandera");
        vTgbtn_Fig8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig8ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig8);

        vTgbtn_Fig9.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig9);
        vTgbtn_Fig9.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig9.setText("Casita");
        vTgbtn_Fig9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig9ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig9);

        vTgbtn_Fig10.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Fig10);
        vTgbtn_Fig10.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Fig10.setText("Corazao");
        vTgbtn_Fig10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_Fig10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_Fig10ActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Fig10);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        vTgbtn_LimpiarPantalla.setBackground(new java.awt.Color(255, 255, 204));
        vTgbtn_LimpiarPantalla.setFont(new java.awt.Font("SimSun", 0, 18)); // NOI18N
        vTgbtn_LimpiarPantalla.setText("Limpiar Figuras");
        vTgbtn_LimpiarPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vTgbtn_LimpiarPantalla.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_LimpiarPantallaActionPerformed(evt);
            }
        });
        jPanel2.add(vTgbtn_LimpiarPantalla);

        vCmbox_ColorDibujado.setFont(new java.awt.Font("SimSun", 0, 11)); // NOI18N
        vCmbox_ColorDibujado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro (Default)", "Rojo", "Verde", "Azul", "Otro" }));
        vCmbox_ColorDibujado.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                vCmbox_ColorDibujadoItemStateChanged(evt);
            }
        });
        vCmbox_ColorDibujado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vCmbox_ColorDibujadoActionPerformed(evt);
            }
        });
        jPanel2.add(vCmbox_ColorDibujado);

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("SimSun", 0, 11)); // NOI18N
        jLabel1.setText("   Opciones de dibujo");
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        vPnlCent.setBackground(new java.awt.Color(204, 255, 204));
        vPnlCent.setLayout(new java.awt.BorderLayout());
        add(vPnlCent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void vTgbtn_Fig1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig1ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig1ActionPerformed
        panel.shapeType = panel.RECTANGLE;
    }//GEN-LAST:event_vTgbtn_Fig1ActionPerformed

    private void vTgbtn_Fig2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig2ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig2ActionPerformed
        panel.shapeType = panel.ELLIPSE2D;
    }//GEN-LAST:event_vTgbtn_Fig2ActionPerformed

    private void vTgbtn_Fig3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig3ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig3ActionPerformed
        panel.shapeType = panel.ROUNDRECTANGLE2D;
    }//GEN-LAST:event_vTgbtn_Fig3ActionPerformed

    private void vTgbtn_Fig4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig4ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig4ActionPerformed
        panel.shapeType = panel.ARC2D;
    }//GEN-LAST:event_vTgbtn_Fig4ActionPerformed

    private void vTgbtn_Fig7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig7ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig7ActionPerformed
        panel.shapeType = panel.LINE2D;
    }//GEN-LAST:event_vTgbtn_Fig7ActionPerformed

    private void vTgbtn_Fig8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig8ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig8ActionPerformed
        panel.shapeType = panel.FLAG;
    }//GEN-LAST:event_vTgbtn_Fig8ActionPerformed

    private void vTgbtn_Fig5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig5ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig5ActionPerformed
        panel.shapeType = panel.QUADCURVE2D;
    }//GEN-LAST:event_vTgbtn_Fig5ActionPerformed

    private void vTgbtn_Fig6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig6ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig6ActionPerformed
        panel.shapeType = panel.POLYGON;
    }//GEN-LAST:event_vTgbtn_Fig6ActionPerformed

    private void vTgbtn_LimpiarPantallaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_LimpiarPantallaActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_LimpiarPantallaActionPerformed
        panel.limpiaPanel();
    }//GEN-LAST:event_vTgbtn_LimpiarPantallaActionPerformed

    private void vTgbtn_Fig10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig10ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig10ActionPerformed
        panel.shapeType = panel.HEARTH;
    }//GEN-LAST:event_vTgbtn_Fig10ActionPerformed

    private void vTgbtn_Fig9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_Fig9ActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_Fig9ActionPerformed
        panel.shapeType = panel.HOUSE;
    }//GEN-LAST:event_vTgbtn_Fig9ActionPerformed

    private void vCmbox_ColorDibujadoItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_vCmbox_ColorDibujadoItemStateChanged
    {//GEN-HEADEREND:event_vCmbox_ColorDibujadoItemStateChanged

    }//GEN-LAST:event_vCmbox_ColorDibujadoItemStateChanged

    private void vCmbox_ColorDibujadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vCmbox_ColorDibujadoActionPerformed
    {//GEN-HEADEREND:event_vCmbox_ColorDibujadoActionPerformed
        JColorChooser colorChooser = new JColorChooser();
        switch (vCmbox_ColorDibujado.getSelectedIndex())
        {
            case 0: //(Negro)
                System.out.println("Negro");
                panel.setvColorDibujado(Color.black);
                break;
            case 1:// Rojo
                System.out.println("Rojo");
                panel.setvColorDibujado(Color.red);
                break;
            case 2: //Verde
                System.out.println("Verde");
                panel.setvColorDibujado(Color.green);
                break;
            case 3: //Azul
                System.out.println("Azul");
                panel.setvColorDibujado(Color.blue);
                break;
            case 4: //Otro
                System.out.println("Otro");
                panel.setvColorDibujado(JColorChooser.showDialog(this, "Seleccione el color de dibujado", panel.getvColorDibujado()));
                break;
        }
        panel.paintComponent(panel.getGraphics());
    }//GEN-LAST:event_vCmbox_ColorDibujadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> vCmbox_ColorDibujado;
    private javax.swing.JPanel vPnlCent;
    private javax.swing.JToggleButton vTgbtn_Fig1;
    private javax.swing.JToggleButton vTgbtn_Fig10;
    private javax.swing.JToggleButton vTgbtn_Fig2;
    private javax.swing.JToggleButton vTgbtn_Fig3;
    private javax.swing.JToggleButton vTgbtn_Fig4;
    private javax.swing.JToggleButton vTgbtn_Fig5;
    private javax.swing.JToggleButton vTgbtn_Fig6;
    private javax.swing.JToggleButton vTgbtn_Fig7;
    private javax.swing.JToggleButton vTgbtn_Fig8;
    private javax.swing.JToggleButton vTgbtn_Fig9;
    private javax.swing.JButton vTgbtn_LimpiarPantalla;
    // End of variables declaration//GEN-END:variables

}
