/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder2;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;

/**
 *
 * @author saipr
 */
public class CPnlAreaGeometryMod extends javax.swing.JPanel
{

    /**
     * Creates new form CPnlAreaGeometryMod
     */
    public CPnlAreaGeometryMod()
    {
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g)
    {
        Graphics2D g2 = (Graphics2D) g;
        Shape s1 = new Ellipse2D.Double(0, 0, 100, 100);
        Shape s2 = new Ellipse2D.Double(60, 0, 100, 100);
        Area a1;
        Area a2 = new Area(s2);
        g2.translate(20, 50);
        g2.draw(s1);
        g2.draw(s2);
        g2.translate(0, 200);
        a1 = new Area(s1);
        a1.add(a2);
        g2.fill(a1);
        g2.translate(180, 0);
        a1 = new Area(s1);
        a1.intersect(a2);
        g2.fill(a1);
        g2.translate(180, 0);
        a1 = new Area(s1);
        a1.subtract(a2);
        g2.fill(a1);
        g2.translate(180, 0);
        a1 = new Area(s1);
        a1.exclusiveOr(a2);
        g2.fill(a1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
