/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder2;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;

/**
 *
 * @author saipr
 */
public class CTestColorPanel extends javax.swing.JPanel
{

    int red = 100;
    int green = 100;
    int blue = 100;

    /**
     * Creates new form ColorPanel
     */
    public CTestColorPanel()
    {
        initComponents();
        setPreferredSize(new Dimension(500, 500));
        setBackground(Color.white);

    }

    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;
        Shape rc = new Ellipse2D.Double(100, 113, 200, 200);
        Shape gc = new Ellipse2D.Double(50, 200, 200, 200);
        Shape bc = new Ellipse2D.Double(150, 200, 200, 200);
        Area ra = new Area(rc);
        Area ga = new Area(gc);
        Area ba = new Area(bc);
        Area rga = new Area(rc);
        rga.intersect(ga);
        Area gba = new Area(gc);
        gba.intersect(ba);
        Area bra = new Area(bc);
        bra.intersect(ra);
        Area rgba = new Area(rga);
        rgba.intersect(ba);
        ra.subtract(rga);
        ra.subtract(bra);
        ga.subtract(rga);
        ga.subtract(gba);
        ba.subtract(bra);
        ba.subtract(gba);
        // fill the color regions
        g2.setColor(new Color(red, 0, 0));
        g2.fill(ra);
        g2.setColor(new Color(0, green, 0));
        g2.fill(ga);
        g2.setColor(new Color(0, 0, blue));
        g2.fill(ba);
        g2.setColor(new Color(red, green, 0));
        g2.fill(rga);
        g2.setColor(new Color(0, green, blue));
        g2.fill(gba);
        g2.setColor(new Color(red, 0, blue));
        g2.fill(bra);
        g2.setColor(new Color(red, green, blue));
        g2.fill(rgba);
        // draw three circles
        g2.setColor(Color.black);
        g2.draw(rc);
        g2.draw(gc);
        g2.draw(bc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
