/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder1;

import java.awt.BorderLayout;
import javax.swing.JSlider;

/**
 *
 * @author saipr
 */
public class CMainTestColorPanel extends javax.swing.JPanel
{

    CTestColorPanel panel;

    /**
     * Creates new form TodoAlv
     */
    public CMainTestColorPanel()
    {

        initComponents();
        panel = new CTestColorPanel();
        panel.setVisible(true);
        this.add(panel, BorderLayout.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSlider2 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSlider3 = new javax.swing.JSlider();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel1.setText("R");
        jPanel2.add(jLabel1);

        jSlider1.setMaximum(255);
        jSlider1.setValue(100);
        jSlider1.setOpaque(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSlider1StateChanged(evt);
            }
        });
        jPanel2.add(jSlider1);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel2.setText("G");
        jPanel3.add(jLabel2);

        jSlider2.setMaximum(255);
        jSlider2.setValue(100);
        jSlider2.setOpaque(false);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSlider2StateChanged(evt);
            }
        });
        jPanel3.add(jSlider2);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 153));

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jLabel3.setText("B");
        jPanel4.add(jLabel3);

        jSlider3.setMaximum(255);
        jSlider3.setValue(100);
        jSlider3.setOpaque(false);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSlider3StateChanged(evt);
            }
        });
        jPanel4.add(jSlider3);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSlider1StateChanged
    {//GEN-HEADEREND:event_jSlider1StateChanged
        panel.red = ((JSlider) (evt.getSource())).getValue();
        panel.repaint();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSlider2StateChanged
    {//GEN-HEADEREND:event_jSlider2StateChanged
        panel.green = ((JSlider) (evt.getSource())).getValue();
        panel.repaint();
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jSlider3StateChanged
    {//GEN-HEADEREND:event_jSlider3StateChanged
        panel.blue = ((JSlider) (evt.getSource())).getValue();
        panel.repaint();
    }//GEN-LAST:event_jSlider3StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    // End of variables declaration//GEN-END:variables
}
