/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder1;


/**
 * @author saipr
 */
public class CPnlDrawShapes extends javax.swing.JPanel
{

    JavaDraw2DPanel panel = null;

    /**
     * Creates new form CPnlDrawShapes
     */
    public CPnlDrawShapes()
    {
        initComponents();
        panel = new JavaDraw2DPanel();
        vPnlCent.add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        vTgbtn_Rectangulo = new javax.swing.JToggleButton();
        vTgbtn_Elipse = new javax.swing.JToggleButton();
        vTgbtn_RectanguloBordeado = new javax.swing.JToggleButton();
        vTgbtn_Arco = new javax.swing.JToggleButton();
        vTgbtn_Linea = new javax.swing.JToggleButton();
        vTgbtn_CurvaCubica = new javax.swing.JToggleButton();
        vTgbtn_CurvaCuadratica = new javax.swing.JToggleButton();
        vTgbtn_Poligono = new javax.swing.JToggleButton();
        vPnlCent = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        vTgbtn_Rectangulo.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Rectangulo);
        vTgbtn_Rectangulo.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Rectangulo.setSelected(true);
        vTgbtn_Rectangulo.setText("Rectangulo");
        vTgbtn_Rectangulo.setBorderPainted(false);
        vTgbtn_Rectangulo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_RectanguloActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Rectangulo);

        vTgbtn_Elipse.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Elipse);
        vTgbtn_Elipse.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Elipse.setText("Elipse");
        vTgbtn_Elipse.setBorderPainted(false);
        vTgbtn_Elipse.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_ElipseActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Elipse);

        vTgbtn_RectanguloBordeado.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_RectanguloBordeado);
        vTgbtn_RectanguloBordeado.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_RectanguloBordeado.setText("Rectagulo Bordeado");
        vTgbtn_RectanguloBordeado.setBorderPainted(false);
        vTgbtn_RectanguloBordeado.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_RectanguloBordeadoActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_RectanguloBordeado);

        vTgbtn_Arco.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Arco);
        vTgbtn_Arco.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Arco.setText("Arco");
        vTgbtn_Arco.setBorderPainted(false);
        vTgbtn_Arco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_ArcoActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Arco);

        vTgbtn_Linea.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Linea);
        vTgbtn_Linea.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Linea.setText("Linea");
        vTgbtn_Linea.setBorderPainted(false);
        vTgbtn_Linea.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_LineaActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Linea);

        vTgbtn_CurvaCubica.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_CurvaCubica);
        vTgbtn_CurvaCubica.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_CurvaCubica.setText("Curva Cubica");
        vTgbtn_CurvaCubica.setBorderPainted(false);
        vTgbtn_CurvaCubica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_CurvaCubicaActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_CurvaCubica);

        vTgbtn_CurvaCuadratica.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_CurvaCuadratica);
        vTgbtn_CurvaCuadratica.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_CurvaCuadratica.setText("Curva Cuadratica");
        vTgbtn_CurvaCuadratica.setBorderPainted(false);
        vTgbtn_CurvaCuadratica.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_CurvaCuadraticaActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_CurvaCuadratica);

        vTgbtn_Poligono.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(vTgbtn_Poligono);
        vTgbtn_Poligono.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        vTgbtn_Poligono.setText("Poligono");
        vTgbtn_Poligono.setBorderPainted(false);
        vTgbtn_Poligono.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vTgbtn_PoligonoActionPerformed(evt);
            }
        });
        jPanel1.add(vTgbtn_Poligono);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        vPnlCent.setBackground(new java.awt.Color(204, 255, 204));
        vPnlCent.setLayout(new java.awt.BorderLayout());
        add(vPnlCent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void vTgbtn_RectanguloActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_RectanguloActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_RectanguloActionPerformed
        panel.setShapeType(panel.RECTANGLE);
    }//GEN-LAST:event_vTgbtn_RectanguloActionPerformed

    private void vTgbtn_ElipseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_ElipseActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_ElipseActionPerformed
        panel.setShapeType(panel.ELLIPSE2D);
    }//GEN-LAST:event_vTgbtn_ElipseActionPerformed

    private void vTgbtn_RectanguloBordeadoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_RectanguloBordeadoActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_RectanguloBordeadoActionPerformed
panel.setShapeType(panel.ROUNDRECTANGLE2D);
    }//GEN-LAST:event_vTgbtn_RectanguloBordeadoActionPerformed

    private void vTgbtn_ArcoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_ArcoActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_ArcoActionPerformed
        panel.setShapeType(panel.ARC2D);
    }//GEN-LAST:event_vTgbtn_ArcoActionPerformed

    private void vTgbtn_LineaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_LineaActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_LineaActionPerformed
        panel.setShapeType(panel.LINE2D);
    }//GEN-LAST:event_vTgbtn_LineaActionPerformed

    private void vTgbtn_CurvaCubicaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_CurvaCubicaActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_CurvaCubicaActionPerformed
         panel.setShapeType(panel.CUBICCURVE2D);
    }//GEN-LAST:event_vTgbtn_CurvaCubicaActionPerformed

    private void vTgbtn_CurvaCuadraticaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_CurvaCuadraticaActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_CurvaCuadraticaActionPerformed
        panel.setShapeType(panel.QUADCURVE2D);
    }//GEN-LAST:event_vTgbtn_CurvaCuadraticaActionPerformed

    private void vTgbtn_PoligonoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vTgbtn_PoligonoActionPerformed
    {//GEN-HEADEREND:event_vTgbtn_PoligonoActionPerformed
        panel.setShapeType(panel.POLYGON);
    }//GEN-LAST:event_vTgbtn_PoligonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel vPnlCent;
    private javax.swing.JToggleButton vTgbtn_Arco;
    private javax.swing.JToggleButton vTgbtn_CurvaCuadratica;
    private javax.swing.JToggleButton vTgbtn_CurvaCubica;
    private javax.swing.JToggleButton vTgbtn_Elipse;
    private javax.swing.JToggleButton vTgbtn_Linea;
    private javax.swing.JToggleButton vTgbtn_Poligono;
    private javax.swing.JToggleButton vTgbtn_Rectangulo;
    private javax.swing.JToggleButton vTgbtn_RectanguloBordeado;
    // End of variables declaration//GEN-END:variables

}
