/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder3;

/**
 *
 * @author saipr
 */
public class Cpnl_FIGURAS_CREADAS extends javax.swing.JPanel
{

    /**
     * Creates new form Cpnl_FIGURAS_CREADAS
     */
    public Cpnl_FIGURAS_CREADAS()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();

        setMaximumSize(new java.awt.Dimension(182, 570));
        setMinimumSize(new java.awt.Dimension(182, 570));
        setPreferredSize(new java.awt.Dimension(182, 570));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(182, 570));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(182, 570));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(182, 570));

        javax.swing.GroupLayout vPnlBotonesLayout = new javax.swing.GroupLayout(vPnlBotones);
        vPnlBotones.setLayout(vPnlBotonesLayout);
        vPnlBotonesLayout.setHorizontalGroup(
            vPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );
        vPnlBotonesLayout.setVerticalGroup(
            vPnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(vPnlBotones);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JPanel vPnlBotones = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}
