/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder3;

import java.awt.Shape;
import java.awt.geom.Area;

/**
 * @author saipr
 */
public class CPnl_EDICION_FIGURAS extends javax.swing.JPanel
{

    public CPnl_EDICION_FIGURAS()
    {
        initComponents();
        mBtnPnlDibujos_CLICKED();
    }

    /**
     * Este metodo recibe una figura la cual contiene todas las configuraciones
     * de los paneles
     *
     */
    public void actualizarPanel()
    {
        //Primero cargo la configuracion del contorno
        //  1.- Tipo del contorno (Solido o Gradiente)
        getRdBtnSolido_CONTORNO().setSelected(false);
        getRdBtnGradiente_CONTORNO().setSelected(false);
        if (Cnfg.CONFIG_COLOR_CONTORNO_2 != null)
        {
            getRdBtnGradiente_CONTORNO().setSelected(true);
        } else
        {
            getRdBtnSolido_CONTORNO().setSelected(true);
            Cnfg.CONFIG_COLOR_CONTORNO_2 = null;
        }
        getvPnlMuestraColor().paintComponent(getvPnlMuestraColor().getGraphics());
        vSpinner_ESPACIADO.setValue(Cnfg.CONFIG_FLOAT_ESPACIO);
        vSpinner_CONTORNO_TAMI.setValue(Cnfg.CONFIG_FLOAT_LINEADO);
        vSpinner_CONTORNO_ANCHO.setValue(Cnfg.CONFIG_FLOAT_ANCHO);
        //Fin de la configuracion del contorno

        //Segundo, configuracion del relleno
        rdBtnSolido_RELLENO.setSelected(false);
        rdBtnGradiente_RELLENO.setSelected(false);
        //rdBtnTextura_RELLENO.setSelected(false);
        if (Cnfg.CONFIG_BUFFERED_IMAGE_RELLENO_3 != null)
        {
            //rdBtnTextura_RELLENO.setSelected(true);
        } else if (Cnfg.CONFIG_COLOR_RELLENO_2 != null)
        {
            rdBtnGradiente_RELLENO.setSelected(true);
        } else
        {
            rdBtnSolido_RELLENO.setSelected(true);
        }
        vPnlMuestraColor_RELLENO.paintComponent(vPnlMuestraColor_RELLENO.getGraphics());
        //Tercero, configuracion de transparencia 
        vSpinner_TRANSPARENCIA.setValue(Cnfg.CONFIG_INT_TRANSPARENCIA);
    }

    private void mBtnPnlDibujos_CLICKED()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        rdBtn_GROUP_CONTORNO = new javax.swing.ButtonGroup();
        rdBtn_GROUP_RELLENO = new javax.swing.ButtonGroup();
        vPnL_CONFIG_CONTORNO = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_CentGeneral_CONTORNO = new javax.swing.JPanel();
        pnlSup_RdBtns = new javax.swing.JPanel();
        rdBtnSolido_CONTORNO = new javax.swing.JRadioButton();
        rdBtnGradiente_CONTORNO = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        vPnlMuestraColor = new folder3.GradientPanel_CONTORNO();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        vSpinner_ESPACIADO = new javax.swing.JSpinner();
        vSpinner_CONTORNO_TAMI = new javax.swing.JSpinner();
        vSpinner_CONTORNO_ANCHO = new javax.swing.JSpinner();
        vPnL_CONFIG_RELLENO = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnl_CentGeneral_CONTORNO1 = new javax.swing.JPanel();
        pnlSup_RdBtns1 = new javax.swing.JPanel();
        rdBtnSolido_RELLENO = new javax.swing.JRadioButton();
        rdBtnGradiente_RELLENO = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        vPnlMuestraColor_RELLENO = new folder3.GradientPanel_RELLENO();
        vPnL_CONFIG_COMPOSICION = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnl_CentGeneral_CONTORNO2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        vSpinner_TRANSPARENCIA = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(182, 600));
        setMinimumSize(new java.awt.Dimension(182, 600));
        setPreferredSize(new java.awt.Dimension(182, 600));
        setLayout(new java.awt.GridBagLayout());

        vPnL_CONFIG_CONTORNO.setForeground(new java.awt.Color(255, 153, 153));
        vPnL_CONFIG_CONTORNO.setMaximumSize(new java.awt.Dimension(145, 55));
        vPnL_CONFIG_CONTORNO.setMinimumSize(new java.awt.Dimension(145, 55));
        vPnL_CONFIG_CONTORNO.setPreferredSize(new java.awt.Dimension(145, 55));
        vPnL_CONFIG_CONTORNO.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel1.setText("Contorno");
        vPnL_CONFIG_CONTORNO.add(jLabel1, java.awt.BorderLayout.NORTH);

        pnl_CentGeneral_CONTORNO.setMaximumSize(new java.awt.Dimension(180, 0));
        pnl_CentGeneral_CONTORNO.setMinimumSize(new java.awt.Dimension(180, 0));
        pnl_CentGeneral_CONTORNO.setPreferredSize(new java.awt.Dimension(180, 0));
        pnl_CentGeneral_CONTORNO.setLayout(new java.awt.BorderLayout());

        pnlSup_RdBtns.setMaximumSize(new java.awt.Dimension(224, 47));
        pnlSup_RdBtns.setMinimumSize(new java.awt.Dimension(224, 47));
        pnlSup_RdBtns.setPreferredSize(new java.awt.Dimension(224, 47));

        rdBtn_GROUP_CONTORNO.add(rdBtnSolido_CONTORNO);
        rdBtnSolido_CONTORNO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdBtnSolido_CONTORNO.setSelected(true);
        rdBtnSolido_CONTORNO.setText("Solido");
        rdBtnSolido_CONTORNO.setBorder(null);
        rdBtnSolido_CONTORNO.setContentAreaFilled(false);
        rdBtnSolido_CONTORNO.setFocusPainted(false);
        rdBtnSolido_CONTORNO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdBtnSolido_CONTORNOActionPerformed(evt);
            }
        });
        pnlSup_RdBtns.add(rdBtnSolido_CONTORNO);

        rdBtn_GROUP_CONTORNO.add(rdBtnGradiente_CONTORNO);
        rdBtnGradiente_CONTORNO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdBtnGradiente_CONTORNO.setText("Gradiente");
        rdBtnGradiente_CONTORNO.setBorder(null);
        rdBtnGradiente_CONTORNO.setContentAreaFilled(false);
        rdBtnGradiente_CONTORNO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdBtnGradiente_CONTORNO.setFocusPainted(false);
        rdBtnGradiente_CONTORNO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdBtnGradiente_CONTORNOActionPerformed(evt);
            }
        });
        pnlSup_RdBtns.add(rdBtnGradiente_CONTORNO);

        pnl_CentGeneral_CONTORNO.add(pnlSup_RdBtns, java.awt.BorderLayout.NORTH);

        jPanel2.setMaximumSize(new java.awt.Dimension(50, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(50, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 500));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        vPnlMuestraColor.setMaximumSize(new java.awt.Dimension(20, 20));
        vPnlMuestraColor.setMinimumSize(new java.awt.Dimension(20, 20));
        vPnlMuestraColor.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.ipady = 55;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        jPanel2.add(vPnlMuestraColor, gridBagConstraints);

        pnl_CentGeneral_CONTORNO.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("Espaciado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel3.setText("Grosor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel4.setText("Contorno:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(jLabel4, gridBagConstraints);

        vSpinner_ESPACIADO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vSpinner_ESPACIADO.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(1.0f)));
        vSpinner_ESPACIADO.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSpinner_ESPACIADOStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(vSpinner_ESPACIADO, gridBagConstraints);

        vSpinner_CONTORNO_TAMI.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vSpinner_CONTORNO_TAMI.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(1.0f), Float.valueOf(20.0f), Float.valueOf(1.0f)));
        vSpinner_CONTORNO_TAMI.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSpinner_CONTORNO_TAMIStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(vSpinner_CONTORNO_TAMI, gridBagConstraints);

        vSpinner_CONTORNO_ANCHO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vSpinner_CONTORNO_ANCHO.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(3.0f), Float.valueOf(1.0f), Float.valueOf(10.0f), Float.valueOf(1.0f)));
        vSpinner_CONTORNO_ANCHO.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSpinner_CONTORNO_ANCHOStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel3.add(vSpinner_CONTORNO_ANCHO, gridBagConstraints);

        pnl_CentGeneral_CONTORNO.add(jPanel3, java.awt.BorderLayout.SOUTH);

        vPnL_CONFIG_CONTORNO.add(pnl_CentGeneral_CONTORNO, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 169;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 5, 0);
        add(vPnL_CONFIG_CONTORNO, gridBagConstraints);

        vPnL_CONFIG_RELLENO.setForeground(new java.awt.Color(255, 153, 153));
        vPnL_CONFIG_RELLENO.setMaximumSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_RELLENO.setMinimumSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_RELLENO.setPreferredSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_RELLENO.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel5.setText("Relleno");
        vPnL_CONFIG_RELLENO.add(jLabel5, java.awt.BorderLayout.NORTH);

        pnl_CentGeneral_CONTORNO1.setMaximumSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO1.setMinimumSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO1.setPreferredSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO1.setLayout(new java.awt.BorderLayout());

        pnlSup_RdBtns1.setMaximumSize(new java.awt.Dimension(224, 47));
        pnlSup_RdBtns1.setMinimumSize(new java.awt.Dimension(224, 47));
        pnlSup_RdBtns1.setPreferredSize(new java.awt.Dimension(224, 47));

        rdBtn_GROUP_RELLENO.add(rdBtnSolido_RELLENO);
        rdBtnSolido_RELLENO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdBtnSolido_RELLENO.setSelected(true);
        rdBtnSolido_RELLENO.setText("Solido");
        rdBtnSolido_RELLENO.setBorder(null);
        rdBtnSolido_RELLENO.setContentAreaFilled(false);
        rdBtnSolido_RELLENO.setFocusPainted(false);
        rdBtnSolido_RELLENO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdBtnSolido_RELLENOActionPerformed(evt);
            }
        });
        pnlSup_RdBtns1.add(rdBtnSolido_RELLENO);

        rdBtn_GROUP_RELLENO.add(rdBtnGradiente_RELLENO);
        rdBtnGradiente_RELLENO.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        rdBtnGradiente_RELLENO.setText("Gradiente");
        rdBtnGradiente_RELLENO.setBorder(null);
        rdBtnGradiente_RELLENO.setContentAreaFilled(false);
        rdBtnGradiente_RELLENO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rdBtnGradiente_RELLENO.setFocusPainted(false);
        rdBtnGradiente_RELLENO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rdBtnGradiente_RELLENOActionPerformed(evt);
            }
        });
        pnlSup_RdBtns1.add(rdBtnGradiente_RELLENO);

        pnl_CentGeneral_CONTORNO1.add(pnlSup_RdBtns1, java.awt.BorderLayout.NORTH);

        jPanel4.setMaximumSize(new java.awt.Dimension(50, 100));
        jPanel4.setMinimumSize(new java.awt.Dimension(50, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        vPnlMuestraColor_RELLENO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vPnlMuestraColor_RELLENO.setMaximumSize(new java.awt.Dimension(20, 20));
        vPnlMuestraColor_RELLENO.setMinimumSize(new java.awt.Dimension(20, 20));
        vPnlMuestraColor_RELLENO.setPreferredSize(new java.awt.Dimension(20, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 55;
        gridBagConstraints.ipady = 55;
        gridBagConstraints.insets = new java.awt.Insets(13, 13, 13, 13);
        jPanel4.add(vPnlMuestraColor_RELLENO, gridBagConstraints);

        pnl_CentGeneral_CONTORNO1.add(jPanel4, java.awt.BorderLayout.CENTER);

        vPnL_CONFIG_RELLENO.add(pnl_CentGeneral_CONTORNO1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 159;
        add(vPnL_CONFIG_RELLENO, gridBagConstraints);

        vPnL_CONFIG_COMPOSICION.setForeground(new java.awt.Color(255, 153, 153));
        vPnL_CONFIG_COMPOSICION.setMaximumSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_COMPOSICION.setMinimumSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_COMPOSICION.setPreferredSize(new java.awt.Dimension(90, 0));
        vPnL_CONFIG_COMPOSICION.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel6.setText("Avanzado");
        vPnL_CONFIG_COMPOSICION.add(jLabel6, java.awt.BorderLayout.NORTH);

        pnl_CentGeneral_CONTORNO2.setMaximumSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO2.setMinimumSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO2.setPreferredSize(new java.awt.Dimension(140, 0));
        pnl_CentGeneral_CONTORNO2.setLayout(new java.awt.BorderLayout());

        jPanel5.setMaximumSize(new java.awt.Dimension(50, 100));
        jPanel5.setMinimumSize(new java.awt.Dimension(50, 100));
        jPanel5.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Transparencia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel5.add(jLabel7, gridBagConstraints);

        vSpinner_TRANSPARENCIA.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        vSpinner_TRANSPARENCIA.setModel(new javax.swing.SpinnerNumberModel(5, 5, 100, 2));
        vSpinner_TRANSPARENCIA.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                vSpinner_TRANSPARENCIAStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel5.add(vSpinner_TRANSPARENCIA, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel8.setText("Transformar:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel5.add(jLabel8, gridBagConstraints);

        vCBox_AFFINE_TRANFORMATIONS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Mover", "Rotar", "Escalar", "Magia", "Reflejar" }));
        vCBox_AFFINE_TRANFORMATIONS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vCBox_AFFINE_TRANFORMATIONSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 2, 0);
        jPanel5.add(vCBox_AFFINE_TRANFORMATIONS, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Operaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 6;
        jPanel5.add(jLabel9, gridBagConstraints);

        vCBox_OPERACIONES_BOOLEANAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna", "Union", "Intersec.", "Sustraer", "XOR" }));
        vCBox_OPERACIONES_BOOLEANAS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                vCBox_OPERACIONES_BOOLEANASActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel5.add(vCBox_OPERACIONES_BOOLEANAS, gridBagConstraints);

        pnl_CentGeneral_CONTORNO2.add(jPanel5, java.awt.BorderLayout.CENTER);

        vPnL_CONFIG_COMPOSICION.add(pnl_CentGeneral_CONTORNO2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.ipady = 105;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(vPnL_CONFIG_COMPOSICION, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnSolido_CONTORNOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdBtnSolido_CONTORNOActionPerformed
    {//GEN-HEADEREND:event_rdBtnSolido_CONTORNOActionPerformed
        Cnfg.CONFIG_COLOR_CONTORNO_2 = null;
        CPnlMainAll.vjPnlEdicionMenu.getvPnlMuestraColor().paintComponent(CPnlMainAll.vjPnlEdicionMenu.getvPnlMuestraColor().getGraphics());
    }//GEN-LAST:event_rdBtnSolido_CONTORNOActionPerformed

    private void rdBtnGradiente_CONTORNOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdBtnGradiente_CONTORNOActionPerformed
    {//GEN-HEADEREND:event_rdBtnGradiente_CONTORNOActionPerformed
        CPnlMainAll.vjPnlEdicionMenu.getvPnlMuestraColor().paintComponent(CPnlMainAll.vjPnlEdicionMenu.getvPnlMuestraColor().getGraphics());
    }//GEN-LAST:event_rdBtnGradiente_CONTORNOActionPerformed

    private void vSpinner_ESPACIADOStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSpinner_ESPACIADOStateChanged
    {//GEN-HEADEREND:event_vSpinner_ESPACIADOStateChanged
        Cnfg.CONFIG_FLOAT_ESPACIO = (float) vSpinner_ESPACIADO.getValue();
        CPnlMainAll.javaDraw2DPanel1.repaint();
    }//GEN-LAST:event_vSpinner_ESPACIADOStateChanged

    private void vSpinner_CONTORNO_TAMIStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSpinner_CONTORNO_TAMIStateChanged
    {//GEN-HEADEREND:event_vSpinner_CONTORNO_TAMIStateChanged
        Cnfg.CONFIG_FLOAT_LINEADO = (float) vSpinner_CONTORNO_TAMI.getValue();
        CPnlMainAll.javaDraw2DPanel1.repaint();
    }//GEN-LAST:event_vSpinner_CONTORNO_TAMIStateChanged

    private void vSpinner_CONTORNO_ANCHOStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSpinner_CONTORNO_ANCHOStateChanged
    {//GEN-HEADEREND:event_vSpinner_CONTORNO_ANCHOStateChanged
        Cnfg.CONFIG_FLOAT_ANCHO = (float) vSpinner_CONTORNO_ANCHO.getValue();
        CPnlMainAll.javaDraw2DPanel1.repaint();
    }//GEN-LAST:event_vSpinner_CONTORNO_ANCHOStateChanged

    private void rdBtnSolido_RELLENOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdBtnSolido_RELLENOActionPerformed
    {//GEN-HEADEREND:event_rdBtnSolido_RELLENOActionPerformed
        Cnfg.CONFIG_COLOR_RELLENO_2 = null;
        CPnlMainAll.vjPnlEdicionMenu.vPnlMuestraColor_RELLENO.paintComponent(CPnlMainAll.vjPnlEdicionMenu.vPnlMuestraColor_RELLENO.getGraphics());
    }//GEN-LAST:event_rdBtnSolido_RELLENOActionPerformed

    private void rdBtnGradiente_RELLENOActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rdBtnGradiente_RELLENOActionPerformed
    {//GEN-HEADEREND:event_rdBtnGradiente_RELLENOActionPerformed
        CPnlMainAll.vjPnlEdicionMenu.vPnlMuestraColor_RELLENO.paintComponent(CPnlMainAll.vjPnlEdicionMenu.vPnlMuestraColor_RELLENO.getGraphics());
    }//GEN-LAST:event_rdBtnGradiente_RELLENOActionPerformed

    private void vSpinner_TRANSPARENCIAStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_vSpinner_TRANSPARENCIAStateChanged
    {//GEN-HEADEREND:event_vSpinner_TRANSPARENCIAStateChanged
        Cnfg.CONFIG_INT_TRANSPARENCIA = (int) vSpinner_TRANSPARENCIA.getValue();
        CPnlMainAll.javaDraw2DPanel1.repaint();
    }//GEN-LAST:event_vSpinner_TRANSPARENCIAStateChanged

    private void vCBox_AFFINE_TRANFORMATIONSActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed
    {//GEN-HEADEREND:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vCBox_AFFINE_TRANFORMATIONSActionPerformed

    private void vCBox_OPERACIONES_BOOLEANASActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_vCBox_OPERACIONES_BOOLEANASActionPerformed
    {//GEN-HEADEREND:event_vCBox_OPERACIONES_BOOLEANASActionPerformed
        if (vCBox_OPERACIONES_BOOLEANAS.getSelectedIndex() != 0)
        {
            Area a = new Area();
            boolean b = false;
            boolean c = false;
            for (int i = 0; i < JavaDraw2DPanel.getShapes().size(); i++)
            {
                if (JavaDraw2DPanel.getShapes().get(i).isSeleccion() && !b)
                {
                    a = new Area(JavaDraw2DPanel.getShapes().get(i).getFigura());
                    b = true;
                    JavaDraw2DPanel.getShapes().remove(i);
                    i--;
                } else if (JavaDraw2DPanel.getShapes().get(i).isSeleccion() && b)
                {
                    Area aAux = new Area(JavaDraw2DPanel.getShapes().get(i).getFigura());
                    switch (vCBox_OPERACIONES_BOOLEANAS.getSelectedIndex())
                    {
                        case Cnfg.CONFIG_INT_OPERACION_BOOLEANA_UNION:
                            a.add(aAux);
                            break;
                        case Cnfg.CONFIG_INT_OPERACION_BOOLEANA_INTERSECCION:
                            a.intersect(aAux);
                            break;
                        case Cnfg.CONFIG_INT_OPERACION_BOOLEANA_SUSTRACCION:
                            a.subtract(aAux);
                            break;
                        case Cnfg.CONFIG_INT_OPERACION_BOOLEANA_XOR:
                            a.exclusiveOr(aAux);
                            break;
                    }
                    JavaDraw2DPanel.getShapes().remove(i);
                    c = true;
                    i--;
                }
            }
            if (c)
            {
                Shape newShape = new Area(a);
                JavaDraw2DPanel.getShapes().add(new CMisFiguras(newShape));
            } else
            {
                System.out.println("Porfavor seleccione minimo de dos figuras, osea no mamen.");
            }
            System.out.println("Figuras en el arreglo = " + JavaDraw2DPanel.getShapes().size());
        }
    }//GEN-LAST:event_vCBox_OPERACIONES_BOOLEANASActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel pnlSup_RdBtns;
    private javax.swing.JPanel pnlSup_RdBtns1;
    private javax.swing.JPanel pnl_CentGeneral_CONTORNO;
    private javax.swing.JPanel pnl_CentGeneral_CONTORNO1;
    private javax.swing.JPanel pnl_CentGeneral_CONTORNO2;
    public static javax.swing.JRadioButton rdBtnGradiente_CONTORNO;
    public static javax.swing.JRadioButton rdBtnGradiente_RELLENO;
    public static javax.swing.JRadioButton rdBtnSolido_CONTORNO;
    public static javax.swing.JRadioButton rdBtnSolido_RELLENO;
    private javax.swing.ButtonGroup rdBtn_GROUP_CONTORNO;
    private javax.swing.ButtonGroup rdBtn_GROUP_RELLENO;
    public static final javax.swing.JComboBox<String> vCBox_AFFINE_TRANFORMATIONS = new javax.swing.JComboBox<>();
    public static final javax.swing.JComboBox<String> vCBox_OPERACIONES_BOOLEANAS = new javax.swing.JComboBox<>();
    private javax.swing.JPanel vPnL_CONFIG_COMPOSICION;
    private javax.swing.JPanel vPnL_CONFIG_CONTORNO;
    private javax.swing.JPanel vPnL_CONFIG_RELLENO;
    private folder3.GradientPanel_CONTORNO vPnlMuestraColor;
    private folder3.GradientPanel_RELLENO vPnlMuestraColor_RELLENO;
    private javax.swing.JSpinner vSpinner_CONTORNO_ANCHO;
    private javax.swing.JSpinner vSpinner_CONTORNO_TAMI;
    private javax.swing.JSpinner vSpinner_ESPACIADO;
    private javax.swing.JSpinner vSpinner_TRANSPARENCIA;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1()
    {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1)
    {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2()
    {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2)
    {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3()
    {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3)
    {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1()
    {
        return vPnL_CONFIG_CONTORNO;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1)
    {
        this.vPnL_CONFIG_CONTORNO = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2()
    {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2)
    {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3()
    {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3)
    {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the pnlSup_RdBtns
     */
    public javax.swing.JPanel getPnlSup_RdBtns()
    {
        return pnlSup_RdBtns;
    }

    /**
     * @param pnlSup_RdBtns the pnlSup_RdBtns to set
     */
    public void setPnlSup_RdBtns(javax.swing.JPanel pnlSup_RdBtns)
    {
        this.pnlSup_RdBtns = pnlSup_RdBtns;
    }

    /**
     * @return the pnl_CentGeneral_CONTORNO
     */
    public javax.swing.JPanel getPnl_CentGeneral_CONTORNO()
    {
        return pnl_CentGeneral_CONTORNO;
    }

    /**
     * @param pnl_CentGeneral_CONTORNO the pnl_CentGeneral_CONTORNO to set
     */
    public void setPnl_CentGeneral_CONTORNO(javax.swing.JPanel pnl_CentGeneral_CONTORNO)
    {
        this.pnl_CentGeneral_CONTORNO = pnl_CentGeneral_CONTORNO;
    }

    /**
     * @return the rdBtnGradiente_CONTORNO
     */
    public static javax.swing.JRadioButton getRdBtnGradiente_CONTORNO()
    {
        return rdBtnGradiente_CONTORNO;
    }

    /**
     * @param aRdBtnGradiente_CONTORNO the rdBtnGradiente_CONTORNO to set
     */
    public static void setRdBtnGradiente_CONTORNO(javax.swing.JRadioButton aRdBtnGradiente_CONTORNO)
    {
        rdBtnGradiente_CONTORNO = aRdBtnGradiente_CONTORNO;
    }

    /**
     * @return the rdBtnSolido_CONTORNO
     */
    public static javax.swing.JRadioButton getRdBtnSolido_CONTORNO()
    {
        return rdBtnSolido_CONTORNO;
    }

    /**
     * @param aRdBtnSolido_CONTORNO the rdBtnSolido_CONTORNO to set
     */
    public static void setRdBtnSolido_CONTORNO(javax.swing.JRadioButton aRdBtnSolido_CONTORNO)
    {
        rdBtnSolido_CONTORNO = aRdBtnSolido_CONTORNO;
    }

    /**
     * @return the rdBtn_GROUP_CONTORNO
     */
    public javax.swing.ButtonGroup getRdBtn_GROUP_CONTORNO()
    {
        return rdBtn_GROUP_CONTORNO;
    }

    /**
     * @param rdBtn_GROUP_CONTORNO the rdBtn_GROUP_CONTORNO to set
     */
    public void setRdBtn_GROUP_CONTORNO(javax.swing.ButtonGroup rdBtn_GROUP_CONTORNO)
    {
        this.rdBtn_GROUP_CONTORNO = rdBtn_GROUP_CONTORNO;
    }

    /**
     * @return the vPnlMuestraColor
     */
    public folder3.GradientPanel_CONTORNO getvPnlMuestraColor()
    {
        return vPnlMuestraColor;
    }

    /**
     * @param vPnlMuestraColor the vPnlMuestraColor to set
     */
    public void setvPnlMuestraColor(folder3.GradientPanel_CONTORNO vPnlMuestraColor)
    {
        this.vPnlMuestraColor = vPnlMuestraColor;
    }

    /**
     * @return the rdBtnSolido_RELLENO
     */
    public static javax.swing.JRadioButton getRdBtnSolido_RELLENO()
    {
        return rdBtnSolido_RELLENO;
    }

    /**
     * @param aRdBtnSolido_RELLENO the rdBtnSolido_RELLENO to set
     */
    public static void setRdBtnSolido_RELLENO(javax.swing.JRadioButton aRdBtnSolido_RELLENO)
    {
        rdBtnSolido_RELLENO = aRdBtnSolido_RELLENO;
    }

    /**
     * @return the rdBtnTextura_RELLENO
     */
    public static javax.swing.JRadioButton getRdBtnTextura_RELLENO()
    {
       return null;
    }

    /**
     * @param aRdBtnTextura_RELLENO the rdBtnTextura_RELLENO to set
     */
    public static void setRdBtnTextura_RELLENO(javax.swing.JRadioButton aRdBtnTextura_RELLENO)
    {
        //rdBtnTextura_RELLENO = aRdBtnTextura_RELLENO;
    }

    /**
     * @return the rdBtn_GROUP_RELLENO
     */
    public javax.swing.ButtonGroup getRdBtn_GROUP_RELLENO()
    {
        return rdBtn_GROUP_RELLENO;
    }

    /**
     * @param rdBtn_GROUP_RELLENO the rdBtn_GROUP_RELLENO to set
     */
    public void setRdBtn_GROUP_RELLENO(javax.swing.ButtonGroup rdBtn_GROUP_RELLENO)
    {
        this.rdBtn_GROUP_RELLENO = rdBtn_GROUP_RELLENO;
    }
}
