/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder3;

/**
 * @author saipr
 */
public class CPnl_FIGURAS_MOD extends javax.swing.JPanel
{

    public int vShapeType;

    public CPnl_FIGURAS_MOD()
    {
        initComponents();
        vShapeType = JavaDraw2DPanel.HEARTH;
        mBtnPnlDibujos_CLICKED();
    }

    private void mBtnPnlDibujos_CLICKED()
    {
        vBtn_CORAZONMouseExited(null);
        vBtn_PENTAGONOMouseExited(null);
        vBtn_ESTRELLA6PMouseExited(null);
        vBtn_CURSORMouseExited(null);
        vBtn_ESTRELLANINJAMouseExited(null);
        vBtn_MURCIELAGOMouseExited(null);
        vBtn_ESCALERASMouseExited(null);
        vBtn_CASITAMouseExited(null);
        vBtn_TRIANGULOMouseExited(null);
        vBtn_ROMBOMouseExited(null);
        switch (vShapeType)
        {
            case JavaDraw2DPanel.HEARTH:
                vBtn_CORAZON.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.HEARTH);
                break;
            case JavaDraw2DPanel.PENTAGON:
                vBtn_PENTAGONO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.PENTAGON);
                break;
            case JavaDraw2DPanel.STAR6P:
                vBtn_ESTRELLA6P.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.STAR6P);
                break;
            case JavaDraw2DPanel.CURSOR:
                vBtn_CURSOR.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.CURSOR);
                break;
            case JavaDraw2DPanel.SHURIKEN:
                vBtn_ESTRELLANINJA.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.SHURIKEN);
                break;
            case JavaDraw2DPanel.BAT:
                vBtn_MURCIELAGO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.BAT);
                break;
            case JavaDraw2DPanel.STAIRS:
                vBtn_ESCALERAS.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.STAIRS);
                break;
            case JavaDraw2DPanel.HOUSE:
                vBtn_CASITA.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.HOUSE);
                break;
            case JavaDraw2DPanel.TRIANGLE:
                vBtn_TRIANGULO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt9.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.TRIANGLE);
                break;
            case JavaDraw2DPanel.RHOMB:
                vBtn_ROMBO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt10.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.RHOMB);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        vBtn_CORAZON = new javax.swing.JPanel();
        vLblTxt1 = new javax.swing.JLabel();
        vLblImg1 = new javax.swing.JLabel();
        vBtn_PENTAGONO = new javax.swing.JPanel();
        vLblTxt2 = new javax.swing.JLabel();
        vLblImg2 = new javax.swing.JLabel();
        vBtn_ESTRELLA6P = new javax.swing.JPanel();
        vLblTxt3 = new javax.swing.JLabel();
        vLblImg3 = new javax.swing.JLabel();
        vBtn_CURSOR = new javax.swing.JPanel();
        vLblTxt4 = new javax.swing.JLabel();
        vLblImg4 = new javax.swing.JLabel();
        vBtn_ESTRELLANINJA = new javax.swing.JPanel();
        vLblTxt5 = new javax.swing.JLabel();
        vLblImg5 = new javax.swing.JLabel();
        vBtn_MURCIELAGO = new javax.swing.JPanel();
        vLblTxt6 = new javax.swing.JLabel();
        vLblImg6 = new javax.swing.JLabel();
        vBtn_ESCALERAS = new javax.swing.JPanel();
        vLblTxt7 = new javax.swing.JLabel();
        vLblImg7 = new javax.swing.JLabel();
        vBtn_CASITA = new javax.swing.JPanel();
        vLblTxt8 = new javax.swing.JLabel();
        vLblImg8 = new javax.swing.JLabel();
        vBtn_TRIANGULO = new javax.swing.JPanel();
        vLblTxt9 = new javax.swing.JLabel();
        vLblImg9 = new javax.swing.JLabel();
        vBtn_ROMBO = new javax.swing.JPanel();
        vLblTxt10 = new javax.swing.JLabel();
        vLblImg10 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(182, 440));
        setLayout(new java.awt.GridBagLayout());

        vBtn_CORAZON.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_CORAZON.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_CORAZON.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_CORAZON.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_CORAZON.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_CORAZONMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_CORAZONMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_CORAZONMouseExited(evt);
            }
        });
        vBtn_CORAZON.setLayout(new java.awt.BorderLayout());

        vLblTxt1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt1.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt1.setText("Corazon");
        vBtn_CORAZON.add(vLblTxt1, java.awt.BorderLayout.SOUTH);

        vLblImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_CORAZON_Ico.png"))); // NOI18N
        vBtn_CORAZON.add(vLblImg1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_CORAZON, gridBagConstraints);

        vBtn_PENTAGONO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_PENTAGONO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_PENTAGONO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_PENTAGONO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_PENTAGONO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_PENTAGONOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_PENTAGONOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_PENTAGONOMouseExited(evt);
            }
        });
        vBtn_PENTAGONO.setLayout(new java.awt.BorderLayout());

        vLblTxt2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt2.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt2.setText("Pentagono");
        vBtn_PENTAGONO.add(vLblTxt2, java.awt.BorderLayout.SOUTH);

        vLblImg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_PENTAGONO_Ico.png"))); // NOI18N
        vBtn_PENTAGONO.add(vLblImg2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_PENTAGONO, gridBagConstraints);

        vBtn_ESTRELLA6P.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ESTRELLA6P.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLA6P.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLA6P.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLA6P.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLA6PMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLA6PMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLA6PMouseExited(evt);
            }
        });
        vBtn_ESTRELLA6P.setLayout(new java.awt.BorderLayout());

        vLblTxt3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt3.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt3.setText("Est. 6 Puntas");
        vBtn_ESTRELLA6P.add(vLblTxt3, java.awt.BorderLayout.SOUTH);

        vLblImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_ESTRELLA6P_Ico.png"))); // NOI18N
        vBtn_ESTRELLA6P.add(vLblImg3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ESTRELLA6P, gridBagConstraints);

        vBtn_CURSOR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_CURSOR.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_CURSOR.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_CURSOR.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_CURSOR.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_CURSORMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_CURSORMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_CURSORMouseExited(evt);
            }
        });
        vBtn_CURSOR.setLayout(new java.awt.BorderLayout());

        vLblTxt4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt4.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt4.setText("Cursor");
        vBtn_CURSOR.add(vLblTxt4, java.awt.BorderLayout.SOUTH);

        vLblImg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/FiguraMOD_CURSOR_Ico.png"))); // NOI18N
        vBtn_CURSOR.add(vLblImg4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_CURSOR, gridBagConstraints);

        vBtn_ESTRELLANINJA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ESTRELLANINJA.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLANINJA.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLANINJA.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ESTRELLANINJA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLANINJAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLANINJAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ESTRELLANINJAMouseExited(evt);
            }
        });
        vBtn_ESTRELLANINJA.setLayout(new java.awt.BorderLayout());

        vLblTxt5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt5.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt5.setText("Shuriken");
        vBtn_ESTRELLANINJA.add(vLblTxt5, java.awt.BorderLayout.SOUTH);

        vLblImg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_ESTRELLANINJA_Ico.png"))); // NOI18N
        vBtn_ESTRELLANINJA.add(vLblImg5, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ESTRELLANINJA, gridBagConstraints);

        vBtn_MURCIELAGO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_MURCIELAGO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_MURCIELAGO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_MURCIELAGO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_MURCIELAGO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_MURCIELAGOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_MURCIELAGOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_MURCIELAGOMouseExited(evt);
            }
        });
        vBtn_MURCIELAGO.setLayout(new java.awt.BorderLayout());

        vLblTxt6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt6.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt6.setText("Batiseñal");
        vBtn_MURCIELAGO.add(vLblTxt6, java.awt.BorderLayout.SOUTH);

        vLblImg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_BATISEÑAL_Ico.png"))); // NOI18N
        vBtn_MURCIELAGO.add(vLblImg6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_MURCIELAGO, gridBagConstraints);

        vBtn_ESCALERAS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ESCALERAS.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ESCALERAS.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ESCALERAS.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ESCALERAS.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ESCALERASMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ESCALERASMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ESCALERASMouseExited(evt);
            }
        });
        vBtn_ESCALERAS.setLayout(new java.awt.BorderLayout());

        vLblTxt7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt7.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt7.setText("Escalera");
        vBtn_ESCALERAS.add(vLblTxt7, java.awt.BorderLayout.SOUTH);

        vLblImg7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_ESCALERAS_Ico.png"))); // NOI18N
        vBtn_ESCALERAS.add(vLblImg7, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ESCALERAS, gridBagConstraints);

        vBtn_CASITA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_CASITA.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_CASITA.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_CASITA.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_CASITA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_CASITAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_CASITAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_CASITAMouseExited(evt);
            }
        });
        vBtn_CASITA.setLayout(new java.awt.BorderLayout());

        vLblTxt8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt8.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt8.setText("Casa");
        vBtn_CASITA.add(vLblTxt8, java.awt.BorderLayout.SOUTH);

        vLblImg8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_CASITA_Ico.png"))); // NOI18N
        vBtn_CASITA.add(vLblImg8, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_CASITA, gridBagConstraints);

        vBtn_TRIANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_TRIANGULO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_TRIANGULO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_TRIANGULO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_TRIANGULO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_TRIANGULOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_TRIANGULOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_TRIANGULOMouseExited(evt);
            }
        });
        vBtn_TRIANGULO.setLayout(new java.awt.BorderLayout());

        vLblTxt9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt9.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt9.setText("Triangulo");
        vBtn_TRIANGULO.add(vLblTxt9, java.awt.BorderLayout.SOUTH);

        vLblImg9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_TRIANGULO_Ico.png"))); // NOI18N
        vBtn_TRIANGULO.add(vLblImg9, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_TRIANGULO, gridBagConstraints);

        vBtn_ROMBO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ROMBO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ROMBO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ROMBO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ROMBO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ROMBOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ROMBOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ROMBOMouseExited(evt);
            }
        });
        vBtn_ROMBO.setLayout(new java.awt.BorderLayout());

        vLblTxt10.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt10.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt10.setText("Rombo");
        vBtn_ROMBO.add(vLblTxt10, java.awt.BorderLayout.SOUTH);

        vLblImg10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/FiguraMOD_ROMBO_Ico.png"))); // NOI18N
        vBtn_ROMBO.add(vLblImg10, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ROMBO, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void vBtn_CORAZONMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CORAZONMouseClicked
    {//GEN-HEADEREND:event_vBtn_CORAZONMouseClicked
        vShapeType = JavaDraw2DPanel.HEARTH;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_CORAZONMouseClicked

    private void vBtn_CORAZONMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CORAZONMouseEntered
    {//GEN-HEADEREND:event_vBtn_CORAZONMouseEntered
        if (vShapeType != JavaDraw2DPanel.HEARTH)
        {
            vBtn_CORAZON.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt1.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_CORAZONMouseEntered

    private void vBtn_CORAZONMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CORAZONMouseExited
    {//GEN-HEADEREND:event_vBtn_CORAZONMouseExited
        if (vShapeType != JavaDraw2DPanel.HEARTH)
        {
            vBtn_CORAZON.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt1.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_CORAZONMouseExited

    private void vBtn_PENTAGONOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_PENTAGONOMouseClicked
    {//GEN-HEADEREND:event_vBtn_PENTAGONOMouseClicked
        vShapeType = JavaDraw2DPanel.PENTAGON;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_PENTAGONOMouseClicked

    private void vBtn_PENTAGONOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_PENTAGONOMouseEntered
    {//GEN-HEADEREND:event_vBtn_PENTAGONOMouseEntered
        if (vShapeType != JavaDraw2DPanel.PENTAGON)
        {
            vBtn_PENTAGONO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt2.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_PENTAGONOMouseEntered

    private void vBtn_PENTAGONOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_PENTAGONOMouseExited
    {//GEN-HEADEREND:event_vBtn_PENTAGONOMouseExited
        if (vShapeType != JavaDraw2DPanel.PENTAGON)
        {
            vBtn_PENTAGONO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt2.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_PENTAGONOMouseExited

    private void vBtn_ESTRELLA6PMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLA6PMouseClicked
    {//GEN-HEADEREND:event_vBtn_ESTRELLA6PMouseClicked
        vShapeType = JavaDraw2DPanel.STAR6P;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ESTRELLA6PMouseClicked

    private void vBtn_ESTRELLA6PMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLA6PMouseEntered
    {//GEN-HEADEREND:event_vBtn_ESTRELLA6PMouseEntered
        if (vShapeType != JavaDraw2DPanel.STAR6P)
        {
            vBtn_ESTRELLA6P.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt3.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ESTRELLA6PMouseEntered

    private void vBtn_ESTRELLA6PMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLA6PMouseExited
    {//GEN-HEADEREND:event_vBtn_ESTRELLA6PMouseExited
        if (vShapeType != JavaDraw2DPanel.STAR6P)
        {
            vBtn_ESTRELLA6P.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt3.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ESTRELLA6PMouseExited

    private void vBtn_CURSORMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CURSORMouseClicked
    {//GEN-HEADEREND:event_vBtn_CURSORMouseClicked
        vShapeType = JavaDraw2DPanel.CURSOR;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_CURSORMouseClicked

    private void vBtn_CURSORMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CURSORMouseEntered
    {//GEN-HEADEREND:event_vBtn_CURSORMouseEntered
        if (vShapeType != JavaDraw2DPanel.CURSOR)
        {
            vBtn_CURSOR.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt4.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_CURSORMouseEntered

    private void vBtn_CURSORMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CURSORMouseExited
    {//GEN-HEADEREND:event_vBtn_CURSORMouseExited
        if (vShapeType != JavaDraw2DPanel.CURSOR)
        {
            vBtn_CURSOR.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt4.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_CURSORMouseExited

    private void vBtn_MURCIELAGOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_MURCIELAGOMouseClicked
    {//GEN-HEADEREND:event_vBtn_MURCIELAGOMouseClicked
        vShapeType = JavaDraw2DPanel.BAT;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_MURCIELAGOMouseClicked

    private void vBtn_MURCIELAGOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_MURCIELAGOMouseEntered
    {//GEN-HEADEREND:event_vBtn_MURCIELAGOMouseEntered
        if (vShapeType != JavaDraw2DPanel.BAT)
        {
            vBtn_MURCIELAGO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt6.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_MURCIELAGOMouseEntered

    private void vBtn_MURCIELAGOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_MURCIELAGOMouseExited
    {//GEN-HEADEREND:event_vBtn_MURCIELAGOMouseExited
        if (vShapeType != JavaDraw2DPanel.BAT)
        {
            vBtn_MURCIELAGO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt6.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_MURCIELAGOMouseExited

    private void vBtn_ESTRELLANINJAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLANINJAMouseClicked
    {//GEN-HEADEREND:event_vBtn_ESTRELLANINJAMouseClicked
        vShapeType = JavaDraw2DPanel.SHURIKEN;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ESTRELLANINJAMouseClicked

    private void vBtn_ESTRELLANINJAMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLANINJAMouseEntered
    {//GEN-HEADEREND:event_vBtn_ESTRELLANINJAMouseEntered
        if (vShapeType != JavaDraw2DPanel.SHURIKEN)
        {
            vBtn_ESTRELLANINJA.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt5.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ESTRELLANINJAMouseEntered

    private void vBtn_ESTRELLANINJAMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESTRELLANINJAMouseExited
    {//GEN-HEADEREND:event_vBtn_ESTRELLANINJAMouseExited
        if (vShapeType != JavaDraw2DPanel.SHURIKEN)
        {
            vBtn_ESTRELLANINJA.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt5.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ESTRELLANINJAMouseExited

    private void vBtn_ESCALERASMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESCALERASMouseClicked
    {//GEN-HEADEREND:event_vBtn_ESCALERASMouseClicked
        vShapeType = JavaDraw2DPanel.STAIRS;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ESCALERASMouseClicked

    private void vBtn_ESCALERASMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESCALERASMouseEntered
    {//GEN-HEADEREND:event_vBtn_ESCALERASMouseEntered
        if (vShapeType != JavaDraw2DPanel.STAIRS)
        {
            vBtn_ESCALERAS.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt7.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ESCALERASMouseEntered

    private void vBtn_ESCALERASMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ESCALERASMouseExited
    {//GEN-HEADEREND:event_vBtn_ESCALERASMouseExited
        if (vShapeType != JavaDraw2DPanel.STAIRS)
        {
            vBtn_ESCALERAS.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt7.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ESCALERASMouseExited

    private void vBtn_CASITAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CASITAMouseClicked
    {//GEN-HEADEREND:event_vBtn_CASITAMouseClicked
        vShapeType = JavaDraw2DPanel.HOUSE;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_CASITAMouseClicked

    private void vBtn_CASITAMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CASITAMouseEntered
    {//GEN-HEADEREND:event_vBtn_CASITAMouseEntered
        if (vShapeType != JavaDraw2DPanel.HOUSE)
        {
            vBtn_CASITA.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt8.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_CASITAMouseEntered

    private void vBtn_CASITAMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CASITAMouseExited
    {//GEN-HEADEREND:event_vBtn_CASITAMouseExited
        if (vShapeType != JavaDraw2DPanel.HOUSE)
        {
            vBtn_CASITA.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt8.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_CASITAMouseExited

    private void vBtn_TRIANGULOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_TRIANGULOMouseClicked
    {//GEN-HEADEREND:event_vBtn_TRIANGULOMouseClicked
        vShapeType = JavaDraw2DPanel.TRIANGLE;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_TRIANGULOMouseClicked

    private void vBtn_TRIANGULOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_TRIANGULOMouseEntered
    {//GEN-HEADEREND:event_vBtn_TRIANGULOMouseEntered
        if (vShapeType != JavaDraw2DPanel.TRIANGLE)
        {
            vBtn_TRIANGULO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt9.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt9.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_TRIANGULOMouseEntered

    private void vBtn_TRIANGULOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_TRIANGULOMouseExited
    {//GEN-HEADEREND:event_vBtn_TRIANGULOMouseExited
        if (vShapeType != JavaDraw2DPanel.TRIANGLE)
        {
            vBtn_TRIANGULO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt9.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt9.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_TRIANGULOMouseExited

    private void vBtn_ROMBOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ROMBOMouseClicked
    {//GEN-HEADEREND:event_vBtn_ROMBOMouseClicked
        vShapeType = JavaDraw2DPanel.RHOMB;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ROMBOMouseClicked

    private void vBtn_ROMBOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ROMBOMouseEntered
    {//GEN-HEADEREND:event_vBtn_ROMBOMouseEntered
        if (vShapeType != JavaDraw2DPanel.RHOMB)
        {
            vBtn_ROMBO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt10.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt10.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ROMBOMouseEntered

    private void vBtn_ROMBOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ROMBOMouseExited
    {//GEN-HEADEREND:event_vBtn_ROMBOMouseExited
        if (vShapeType != JavaDraw2DPanel.RHOMB)
        {
            vBtn_ROMBO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt10.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt10.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ROMBOMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel vBtn_CASITA;
    private javax.swing.JPanel vBtn_CORAZON;
    private javax.swing.JPanel vBtn_CURSOR;
    private javax.swing.JPanel vBtn_ESCALERAS;
    private javax.swing.JPanel vBtn_ESTRELLA6P;
    private javax.swing.JPanel vBtn_ESTRELLANINJA;
    private javax.swing.JPanel vBtn_MURCIELAGO;
    private javax.swing.JPanel vBtn_PENTAGONO;
    private javax.swing.JPanel vBtn_ROMBO;
    private javax.swing.JPanel vBtn_TRIANGULO;
    private javax.swing.JLabel vLblImg1;
    private javax.swing.JLabel vLblImg10;
    private javax.swing.JLabel vLblImg2;
    private javax.swing.JLabel vLblImg3;
    private javax.swing.JLabel vLblImg4;
    private javax.swing.JLabel vLblImg5;
    private javax.swing.JLabel vLblImg6;
    private javax.swing.JLabel vLblImg7;
    private javax.swing.JLabel vLblImg8;
    private javax.swing.JLabel vLblImg9;
    private javax.swing.JLabel vLblTxt1;
    private javax.swing.JLabel vLblTxt10;
    private javax.swing.JLabel vLblTxt2;
    private javax.swing.JLabel vLblTxt3;
    private javax.swing.JLabel vLblTxt4;
    private javax.swing.JLabel vLblTxt5;
    private javax.swing.JLabel vLblTxt6;
    private javax.swing.JLabel vLblTxt7;
    private javax.swing.JLabel vLblTxt8;
    private javax.swing.JLabel vLblTxt9;
    // End of variables declaration//GEN-END:variables
}
