/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package folder3;

/**
 * @author saipr
 */
public class CPnl_FIGURAS_2D extends javax.swing.JPanel
{

    public static int vShapeType;

    public CPnl_FIGURAS_2D()
    {
        initComponents();
        vShapeType = JavaDraw2DPanel.LINE2D;
        mBtnPnlDibujos_CLICKED();
    }

    private void mBtnPnlDibujos_CLICKED()
    {
        vBtn_LINEAMouseExited(null);
        vBtn_ELIPSEMouseExited(null);
        vBtn_RECTANGULOMouseExited(null);
        vBtn_RECTANGULOMouseExited(null);
        vBtn_RECTANGULO2MouseExited(null);
        vBtn_ARCOMouseExited(null);
        vBtn_CUADRATICAMouseExited(null);
        vBtn_CUBICAMouseExited(null);
        vBtn_POLIGONOMouseExited(null);
        switch (vShapeType)
        {
            case JavaDraw2DPanel.LINE2D:
                vBtn_LINEA.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.LINE2D);
                break;
            case JavaDraw2DPanel.ELLIPSE2D:
                vBtn_ELIPSE.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.ELLIPSE2D);
                break;
            case JavaDraw2DPanel.RECTANGLE:
                vBtn_RECTANGULO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.RECTANGLE);
                break;
            case JavaDraw2DPanel.ROUNDRECTANGLE2D:
                vBtn_RECTANGULO2.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.ROUNDRECTANGLE2D);
                break;
            case JavaDraw2DPanel.ARC2D:
                vBtn_ARCO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.ARC2D);
                break;
            case JavaDraw2DPanel.QUADCURVE2D:
                vBtn_CUADRATICA.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.QUADCURVE2D);
                break;
            case JavaDraw2DPanel.CUBICCURVE2D:
                vBtn_CUBICA.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.CUBICCURVE2D);
                break;
            case JavaDraw2DPanel.POLYGON:
                vBtn_POLIGONO.setBackground(Cnfg.MOUSE_JPANEL_CLICKED);
                vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_CLICKED);
                CPnlMainAll.setvShapeType(JavaDraw2DPanel.POLYGON);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        vBtn_LINEA = new javax.swing.JPanel();
        vLblTxt1 = new javax.swing.JLabel();
        vLblImg1 = new javax.swing.JLabel();
        vBtn_ELIPSE = new javax.swing.JPanel();
        vLblTxt2 = new javax.swing.JLabel();
        vLblImg2 = new javax.swing.JLabel();
        vBtn_RECTANGULO = new javax.swing.JPanel();
        vLblTxt3 = new javax.swing.JLabel();
        vLblImg3 = new javax.swing.JLabel();
        vBtn_RECTANGULO2 = new javax.swing.JPanel();
        vLblTxt4 = new javax.swing.JLabel();
        vLblImg4 = new javax.swing.JLabel();
        vBtn_ARCO = new javax.swing.JPanel();
        vLblTxt5 = new javax.swing.JLabel();
        vLblImg5 = new javax.swing.JLabel();
        vBtn_CUADRATICA = new javax.swing.JPanel();
        vLblTxt6 = new javax.swing.JLabel();
        vLblImg6 = new javax.swing.JLabel();
        vBtn_CUBICA = new javax.swing.JPanel();
        vLblTxt7 = new javax.swing.JLabel();
        vLblImg7 = new javax.swing.JLabel();
        vBtn_POLIGONO = new javax.swing.JPanel();
        vLblTxt8 = new javax.swing.JLabel();
        vLblImg8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(182, 352));
        setLayout(new java.awt.GridBagLayout());

        vBtn_LINEA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_LINEA.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_LINEA.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_LINEA.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_LINEA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_LINEAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_LINEAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_LINEAMouseExited(evt);
            }
        });
        vBtn_LINEA.setLayout(new java.awt.BorderLayout());

        vLblTxt1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt1.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt1.setText("Linea");
        vBtn_LINEA.add(vLblTxt1, java.awt.BorderLayout.SOUTH);

        vLblImg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_Linea_Ico.png"))); // NOI18N
        vBtn_LINEA.add(vLblImg1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_LINEA, gridBagConstraints);

        vBtn_ELIPSE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ELIPSE.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ELIPSE.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ELIPSE.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ELIPSE.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ELIPSEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ELIPSEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ELIPSEMouseExited(evt);
            }
        });
        vBtn_ELIPSE.setLayout(new java.awt.BorderLayout());

        vLblTxt2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt2.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt2.setText("Elipse");
        vBtn_ELIPSE.add(vLblTxt2, java.awt.BorderLayout.SOUTH);

        vLblImg2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_ELIPSE_Ico.png"))); // NOI18N
        vBtn_ELIPSE.add(vLblImg2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ELIPSE, gridBagConstraints);

        vBtn_RECTANGULO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_RECTANGULO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULOMouseExited(evt);
            }
        });
        vBtn_RECTANGULO.setLayout(new java.awt.BorderLayout());

        vLblTxt3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt3.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt3.setText("Rectangulo");
        vBtn_RECTANGULO.add(vLblTxt3, java.awt.BorderLayout.SOUTH);

        vLblImg3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_RECTANGULO_Ico.png"))); // NOI18N
        vBtn_RECTANGULO.add(vLblImg3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_RECTANGULO, gridBagConstraints);

        vBtn_RECTANGULO2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_RECTANGULO2.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO2.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO2.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_RECTANGULO2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULO2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULO2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_RECTANGULO2MouseExited(evt);
            }
        });
        vBtn_RECTANGULO2.setLayout(new java.awt.BorderLayout());

        vLblTxt4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt4.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt4.setText("Rect. Bord.");
        vBtn_RECTANGULO2.add(vLblTxt4, java.awt.BorderLayout.SOUTH);

        vLblImg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_RECTANGULO2_Ico.png"))); // NOI18N
        vBtn_RECTANGULO2.add(vLblImg4, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_RECTANGULO2, gridBagConstraints);

        vBtn_ARCO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_ARCO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_ARCO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_ARCO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_ARCO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_ARCOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_ARCOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_ARCOMouseExited(evt);
            }
        });
        vBtn_ARCO.setLayout(new java.awt.BorderLayout());

        vLblTxt5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt5.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt5.setText("Arco");
        vBtn_ARCO.add(vLblTxt5, java.awt.BorderLayout.SOUTH);

        vLblImg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_ARCO_Ico.png"))); // NOI18N
        vBtn_ARCO.add(vLblImg5, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_ARCO, gridBagConstraints);

        vBtn_CUADRATICA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_CUADRATICA.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_CUADRATICA.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_CUADRATICA.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_CUADRATICA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_CUADRATICAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_CUADRATICAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_CUADRATICAMouseExited(evt);
            }
        });
        vBtn_CUADRATICA.setLayout(new java.awt.BorderLayout());

        vLblTxt6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt6.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt6.setText("Cuadratica");
        vBtn_CUADRATICA.add(vLblTxt6, java.awt.BorderLayout.SOUTH);

        vLblImg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_CUADRATICA_Ico.png"))); // NOI18N
        vBtn_CUADRATICA.add(vLblImg6, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_CUADRATICA, gridBagConstraints);

        vBtn_CUBICA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_CUBICA.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_CUBICA.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_CUBICA.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_CUBICA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_CUBICAMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_CUBICAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_CUBICAMouseExited(evt);
            }
        });
        vBtn_CUBICA.setLayout(new java.awt.BorderLayout());

        vLblTxt7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt7.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt7.setText("Cubica");
        vBtn_CUBICA.add(vLblTxt7, java.awt.BorderLayout.SOUTH);

        vLblImg7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_CUBICA_Ico.png"))); // NOI18N
        vBtn_CUBICA.add(vLblImg7, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_CUBICA, gridBagConstraints);

        vBtn_POLIGONO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vBtn_POLIGONO.setMaximumSize(new java.awt.Dimension(61, 58));
        vBtn_POLIGONO.setMinimumSize(new java.awt.Dimension(61, 58));
        vBtn_POLIGONO.setPreferredSize(new java.awt.Dimension(61, 58));
        vBtn_POLIGONO.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                vBtn_POLIGONOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                vBtn_POLIGONOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                vBtn_POLIGONOMouseExited(evt);
            }
        });
        vBtn_POLIGONO.setLayout(new java.awt.BorderLayout());

        vLblTxt8.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        vLblTxt8.setForeground(new java.awt.Color(255, 0, 51));
        vLblTxt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblTxt8.setText("Poligono");
        vBtn_POLIGONO.add(vLblTxt8, java.awt.BorderLayout.SOUTH);

        vLblImg8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vLblImg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Figura2D_POLIGONO_Ico.png"))); // NOI18N
        vBtn_POLIGONO.add(vLblImg8, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 30;
        add(vBtn_POLIGONO, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void vBtn_LINEAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_LINEAMouseClicked
    {//GEN-HEADEREND:event_vBtn_LINEAMouseClicked
        vShapeType = JavaDraw2DPanel.LINE2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_LINEAMouseClicked

    private void vBtn_LINEAMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_LINEAMouseEntered
    {//GEN-HEADEREND:event_vBtn_LINEAMouseEntered
        if (vShapeType != JavaDraw2DPanel.LINE2D)
        {
            vBtn_LINEA.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt1.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_LINEAMouseEntered

    private void vBtn_LINEAMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_LINEAMouseExited
    {//GEN-HEADEREND:event_vBtn_LINEAMouseExited
        if (vShapeType != JavaDraw2DPanel.LINE2D)
        {
            vBtn_LINEA.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt1.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt1.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_LINEAMouseExited

    private void vBtn_ELIPSEMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ELIPSEMouseClicked
    {//GEN-HEADEREND:event_vBtn_ELIPSEMouseClicked
        vShapeType = JavaDraw2DPanel.ELLIPSE2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ELIPSEMouseClicked

    private void vBtn_ELIPSEMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ELIPSEMouseEntered
    {//GEN-HEADEREND:event_vBtn_ELIPSEMouseEntered
        if (vShapeType != JavaDraw2DPanel.ELLIPSE2D)
        {
            vBtn_ELIPSE.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt2.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ELIPSEMouseEntered

    private void vBtn_ELIPSEMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ELIPSEMouseExited
    {//GEN-HEADEREND:event_vBtn_ELIPSEMouseExited
        if (vShapeType != JavaDraw2DPanel.ELLIPSE2D)
        {
            vBtn_ELIPSE.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt2.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt2.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ELIPSEMouseExited

    private void vBtn_RECTANGULOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULOMouseClicked
    {//GEN-HEADEREND:event_vBtn_RECTANGULOMouseClicked
        vShapeType = JavaDraw2DPanel.RECTANGLE;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_RECTANGULOMouseClicked

    private void vBtn_RECTANGULOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULOMouseEntered
    {//GEN-HEADEREND:event_vBtn_RECTANGULOMouseEntered
        if (vShapeType != JavaDraw2DPanel.RECTANGLE)
        {
            vBtn_RECTANGULO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt3.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_RECTANGULOMouseEntered

    private void vBtn_RECTANGULOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULOMouseExited
    {//GEN-HEADEREND:event_vBtn_RECTANGULOMouseExited
        if (vShapeType != JavaDraw2DPanel.RECTANGLE)
        {
            vBtn_RECTANGULO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt3.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt3.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_RECTANGULOMouseExited

    private void vBtn_RECTANGULO2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULO2MouseClicked
    {//GEN-HEADEREND:event_vBtn_RECTANGULO2MouseClicked
        vShapeType = JavaDraw2DPanel.ROUNDRECTANGLE2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_RECTANGULO2MouseClicked

    private void vBtn_RECTANGULO2MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULO2MouseEntered
    {//GEN-HEADEREND:event_vBtn_RECTANGULO2MouseEntered
        if (vShapeType != JavaDraw2DPanel.ROUNDRECTANGLE2D)
        {
            vBtn_RECTANGULO2.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt4.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_RECTANGULO2MouseEntered

    private void vBtn_RECTANGULO2MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_RECTANGULO2MouseExited
    {//GEN-HEADEREND:event_vBtn_RECTANGULO2MouseExited
        if (vShapeType != JavaDraw2DPanel.ROUNDRECTANGLE2D)
        {
            vBtn_RECTANGULO2.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt4.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt4.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_RECTANGULO2MouseExited

    private void vBtn_CUADRATICAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUADRATICAMouseClicked
    {//GEN-HEADEREND:event_vBtn_CUADRATICAMouseClicked
        vShapeType = JavaDraw2DPanel.QUADCURVE2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_CUADRATICAMouseClicked

    private void vBtn_CUADRATICAMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUADRATICAMouseEntered
    {//GEN-HEADEREND:event_vBtn_CUADRATICAMouseEntered
        if (vShapeType != JavaDraw2DPanel.QUADCURVE2D)
        {
            vBtn_CUADRATICA.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt6.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_CUADRATICAMouseEntered

    private void vBtn_CUADRATICAMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUADRATICAMouseExited
    {//GEN-HEADEREND:event_vBtn_CUADRATICAMouseExited
        if (vShapeType != JavaDraw2DPanel.QUADCURVE2D)
        {
            vBtn_CUADRATICA.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt6.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt6.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_CUADRATICAMouseExited

    private void vBtn_ARCOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ARCOMouseClicked
    {//GEN-HEADEREND:event_vBtn_ARCOMouseClicked
        vShapeType = JavaDraw2DPanel.ARC2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_ARCOMouseClicked

    private void vBtn_ARCOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ARCOMouseEntered
    {//GEN-HEADEREND:event_vBtn_ARCOMouseEntered
        if (vShapeType != JavaDraw2DPanel.ARC2D)
        {
            vBtn_ARCO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt5.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_ARCOMouseEntered

    private void vBtn_ARCOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_ARCOMouseExited
    {//GEN-HEADEREND:event_vBtn_ARCOMouseExited
        if (vShapeType != JavaDraw2DPanel.ARC2D)
        {
            vBtn_ARCO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt5.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt5.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_ARCOMouseExited

    private void vBtn_CUBICAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUBICAMouseClicked
    {//GEN-HEADEREND:event_vBtn_CUBICAMouseClicked
        vShapeType = JavaDraw2DPanel.CUBICCURVE2D;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_CUBICAMouseClicked

    private void vBtn_CUBICAMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUBICAMouseEntered
    {//GEN-HEADEREND:event_vBtn_CUBICAMouseEntered
        if (vShapeType != JavaDraw2DPanel.CUBICCURVE2D)
        {
            vBtn_CUBICA.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt7.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_CUBICAMouseEntered

    private void vBtn_CUBICAMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_CUBICAMouseExited
    {//GEN-HEADEREND:event_vBtn_CUBICAMouseExited
        if (vShapeType != JavaDraw2DPanel.CUBICCURVE2D)
        {
            vBtn_CUBICA.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt7.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt7.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_CUBICAMouseExited

    private void vBtn_POLIGONOMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_POLIGONOMouseClicked
    {//GEN-HEADEREND:event_vBtn_POLIGONOMouseClicked
        vShapeType = JavaDraw2DPanel.POLYGON;
        mBtnPnlDibujos_CLICKED();
    }//GEN-LAST:event_vBtn_POLIGONOMouseClicked

    private void vBtn_POLIGONOMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_POLIGONOMouseEntered
    {//GEN-HEADEREND:event_vBtn_POLIGONOMouseEntered
        if (vShapeType != JavaDraw2DPanel.POLYGON)
        {
            vBtn_POLIGONO.setBackground(Cnfg.MOUSE_JPANEL_ENTERED);
            vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_ENTERED);
            vLblTxt8.setFont(Cnfg.FONT_TEXTO_ENTERED);
        }
    }//GEN-LAST:event_vBtn_POLIGONOMouseEntered

    private void vBtn_POLIGONOMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_vBtn_POLIGONOMouseExited
    {//GEN-HEADEREND:event_vBtn_POLIGONOMouseExited
        if (vShapeType != JavaDraw2DPanel.POLYGON)
        {
            vBtn_POLIGONO.setBackground(Cnfg.MOUSE_JPANEL_EXITED);
            vLblTxt8.setForeground(Cnfg.MOUSE_TEXTO_EXITED);
            vLblTxt8.setFont(Cnfg.FONT_TEXTO_EXITED);
        }
    }//GEN-LAST:event_vBtn_POLIGONOMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel vBtn_ARCO;
    private javax.swing.JPanel vBtn_CUADRATICA;
    private javax.swing.JPanel vBtn_CUBICA;
    private javax.swing.JPanel vBtn_ELIPSE;
    private javax.swing.JPanel vBtn_LINEA;
    private javax.swing.JPanel vBtn_POLIGONO;
    private javax.swing.JPanel vBtn_RECTANGULO;
    private javax.swing.JPanel vBtn_RECTANGULO2;
    private javax.swing.JLabel vLblImg1;
    private javax.swing.JLabel vLblImg2;
    private javax.swing.JLabel vLblImg3;
    private javax.swing.JLabel vLblImg4;
    private javax.swing.JLabel vLblImg5;
    private javax.swing.JLabel vLblImg6;
    private javax.swing.JLabel vLblImg7;
    private javax.swing.JLabel vLblImg8;
    private javax.swing.JLabel vLblTxt1;
    private javax.swing.JLabel vLblTxt2;
    private javax.swing.JLabel vLblTxt3;
    private javax.swing.JLabel vLblTxt4;
    private javax.swing.JLabel vLblTxt5;
    private javax.swing.JLabel vLblTxt6;
    private javax.swing.JLabel vLblTxt7;
    private javax.swing.JLabel vLblTxt8;
    // End of variables declaration//GEN-END:variables
}
